### ISSUE TITLE
Can't access authenticated routes

### ISSUE THREAD

**Issue by sazid-hassan** [Innovix-Matrix-Systems/ims-nest-api-starter#18]
After logging & sending the JWT token, I can't access the authenticated routes.

![image](https://github.com/user-attachments/assets/be9c3fa0-e25a-4516-91a5-1981b9c68846)

If I disable the guards, then I can access the routes.

**Comment by AHS12** [comment]
I have done some investigation, I have found that The key issue is in the expiration timing. I will create a PR soon for this fix

**Comment by AHS12** [comment]
It should be fixed now.
